from pymolt.ingestion.conda_ingest import parse_environment_yaml, parse_conda_lock_yaml
from pymolt.ingestion.uv_runner import parse_uv_compile_output
from pymolt.ingestion.name_mapping import parse_grayskull_yaml, NameMapper


def test_parse_environment_yaml():
    yaml_content = """
name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=1.22
  - pip:
    - requests==2.31.0
    - flask
"""
    parsed = parse_environment_yaml(yaml_content)
    assert parsed["dependencies"] == ["python=3.12", "numpy>=1.22"]
    assert parsed["pip"] == ["requests==2.31.0", "flask"]


def test_parse_conda_lock_yaml():
    lock_content = """
metadata:
  version: 1
package:
  - name: numpy
    version: 1.24.3
    manager: conda
  - name: requests
    version: 2.31.0
    manager: pip
"""
    parsed = parse_conda_lock_yaml(lock_content)
    assert len(parsed) == 2
    assert parsed[0] == {"name": "numpy", "version": "1.24.3", "manager": "conda"}
    assert parsed[1] == {"name": "requests", "version": "2.31.0", "manager": "pip"}


def test_parse_uv_compile_output():
    compile_output = """
# This file was autogenerated by uv via pip compile.
anyio==4.3.0
    # via httpx
httpx==0.27.0
    # via -r requirements.in
"""
    graph = parse_uv_compile_output(compile_output, "requirements.in")
    assert "anyio" in graph.nodes
    assert "httpx" in graph.nodes
    
    assert graph.nodes["httpx"].direct is True
    assert graph.nodes["anyio"].direct is False
    
    # We should have an edge: httpx -> anyio
    edge = graph.edges[0]
    assert edge.source == "httpx"
    assert edge.target == "anyio"


def test_parse_grayskull_yaml():
    yaml_content = """
# grayskull config
pyyaml:
  conda_forge: pyyaml
  import_name: yaml
pytorch:
  conda_forge: pytorch
  import_name: torch
"""
    parsed = parse_grayskull_yaml(yaml_content)
    assert parsed["pyyaml"] == {"conda_forge": "pyyaml", "import_name": "yaml"}
    assert parsed["pytorch"] == {"conda_forge": "pytorch", "import_name": "torch"}


def test_name_mapper_cascade():
    mapper = NameMapper()

    # Known name/import divergence resolves authoritatively from the bundled map.
    mapping1 = mapper.conda_to_pypi("pyyaml")
    assert mapping1.pypi_name == "PyYAML"
    assert mapping1.import_name == "yaml"
    assert mapping1.confidence == "authoritative"

    # Unknown package falls back to heuristic self-name normalization.
    mapping2 = mapper.conda_to_pypi("scikit-learn")
    assert mapping2.pypi_name == "scikit-learn"
    assert mapping2.import_name == "scikit_learn"
    assert mapping2.confidence == "heuristic"


def test_parse_uv_compile_output_with_declared_reqs():
    compile_output = """
# This file was autogenerated by uv via pip compile.
flask==2.2.5
    # via -r requirements.txt
jsonschema==4.17.3
    # via -r requirements.txt
six==1.17.0
    # via flask
"""
    declared = {
        "flask": "Flask>=0.10",
        "jsonschema": "jsonschema>=3.0.1"
    }
    graph = parse_uv_compile_output(compile_output, "requirements.txt", declared)
    assert graph.nodes["flask"].declared_requirement == "Flask>=0.10"
    assert graph.nodes["jsonschema"].declared_requirement == "jsonschema>=3.0.1"
    assert graph.nodes["six"].declared_requirement is None
