from pymolt.ingestion.detect import detect_sources, _classify_requirements_fixation, _classify_pyproject_fixation
from pymolt.core.enums import Mode, SourceFixation


def test_detect_sources_empty(tmp_path):
    sources = detect_sources(tmp_path)
    assert isinstance(sources, list)
    assert len(sources) == 0


def test_detect_skips_pymolt_generated_target_manifests(tmp_path):
    # assess's own output must never be re-ingested as an input (regression: it
    # used to crash the next run's pip-compile on the pinned --hash file).
    (tmp_path / "requirements.txt").write_text("flask>=2.0\n", encoding="utf-8")
    (tmp_path / "requirements-target.txt").write_text(
        "# Generated by pymolt audit for Python 3.12\nflask==3.0.0\n", encoding="utf-8"
    )
    # also excluded by the header marker even if renamed
    (tmp_path / "resolved-out.txt").write_text(
        "# Generated by pymolt audit for Python 3.12\nx==1\n", encoding="utf-8"
    )
    names = sorted(s.path.name for s in detect_sources(tmp_path))
    assert names == ["requirements.txt"]


def test_classify_requirements_fixation(tmp_path):
    # Pinned requirements
    pinned_file = tmp_path / "requirements.txt"
    pinned_file.write_text("requests==2.31.0\n# comment\npytest==8.0.0\n", encoding="utf-8")
    assert _classify_requirements_fixation(pinned_file) == SourceFixation.PINNED

    # Intent requirements
    intent_file = tmp_path / "requirements.in"
    intent_file.write_text("requests\npytest\n", encoding="utf-8")
    assert _classify_requirements_fixation(intent_file) == SourceFixation.INTENT

    # Mixed requirements
    mixed_file = tmp_path / "requirements_mixed.txt"
    mixed_file.write_text("requests==2.31.0\npytest\n", encoding="utf-8")
    assert _classify_requirements_fixation(mixed_file) == SourceFixation.MIXED


def test_classify_pyproject_fixation(tmp_path):
    pyproject_file = tmp_path / "pyproject.toml"
    
    # Intent/unpinned dependencies
    pyproject_file.write_text("""
[project]
dependencies = [
    "requests>=2.0",
    "pytest",
]
""", encoding="utf-8")
    assert _classify_pyproject_fixation(pyproject_file) == SourceFixation.INTENT

    # Pinned dependencies
    pyproject_file.write_text("""
[project]
dependencies = [
    "requests==2.31.0",
    "pytest==8.0.0",
]
""", encoding="utf-8")
    assert _classify_pyproject_fixation(pyproject_file) == SourceFixation.PINNED


def test_classify_requirements_fixation_edge_cases(tmp_path):
    # An environment marker with '<' must not fool the classifier: the spec is
    # still exactly pinned.
    marked = tmp_path / "requirements.txt"
    marked.write_text('requests==2.31.0 ; python_version < "3.8"\n', encoding="utf-8")
    assert _classify_requirements_fixation(marked) == SourceFixation.PINNED

    # Compatible-release (~=) and ranges are NOT pins.
    loose = tmp_path / "requirements_loose.txt"
    loose.write_text("requests~=2.31\nflask>=2.0,<3.0\n", encoding="utf-8")
    assert _classify_requirements_fixation(loose) == SourceFixation.INTENT

    # A direct URL/VCS reference counts as pinned.
    url = tmp_path / "requirements_url.txt"
    url.write_text("foo @ git+https://example.com/foo.git@abc123\n", encoding="utf-8")
    assert _classify_requirements_fixation(url) == SourceFixation.PINNED

    # Inline comments are stripped, not parsed as part of the spec.
    commented = tmp_path / "requirements_comment.txt"
    commented.write_text("requests==2.31.0  # keep pinned\n", encoding="utf-8")
    assert _classify_requirements_fixation(commented) == SourceFixation.PINNED


def test_classify_pyproject_fixation_marker_not_fooled(tmp_path):
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        '[project]\ndependencies = [\n  "requests==2.31.0 ; python_version < \'3.8\'",\n  "flask==3.0.0",\n]\n',
        encoding="utf-8",
    )
    assert _classify_pyproject_fixation(pyproject) == SourceFixation.PINNED


def test_detect_sources_conda_and_locks(tmp_path):
    (tmp_path / "environment.yml").write_text("name: test", encoding="utf-8")
    (tmp_path / "conda-lock.yml").write_text("package:", encoding="utf-8")
    (tmp_path / "poetry.lock").write_text("metadata:", encoding="utf-8")
    (tmp_path / "uv.lock").write_text("manifest:", encoding="utf-8")
    
    sources = detect_sources(tmp_path)
    # Should find 4 sources
    assert len(sources) == 4
    
    modes = {s.path.name: s.mode for s in sources}
    assert modes["environment.yml"] == Mode.CONDA
    assert modes["conda-lock.yml"] == Mode.CONDA
    assert modes["poetry.lock"] == Mode.PYPI
    assert modes["uv.lock"] == Mode.PYPI

    locks = {s.path.name: s.is_lock for s in sources}
    assert locks["environment.yml"] is False
    assert locks["conda-lock.yml"] is True
    assert locks["poetry.lock"] is True
    assert locks["uv.lock"] is True


from pymolt.ingestion.detect import detect_project_python_version, extract_declared_requirements

def test_detect_project_python_version(tmp_path):
    # Test .python-version
    (tmp_path / ".python-version").write_text("3.6.1\n", encoding="utf-8")
    assert detect_project_python_version(tmp_path) == "3.6.1"
    (tmp_path / ".python-version").unlink()

    # Test pyproject.toml
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text("[project]\nrequires-python = \">=3.8\"\n", encoding="utf-8")
    assert detect_project_python_version(tmp_path) == "3.8"
    pyproject.unlink()

    # Test Pipfile
    pipfile = tmp_path / "Pipfile"
    pipfile.write_text("[requires]\npython_version = \"3.11\"\n", encoding="utf-8")
    assert detect_project_python_version(tmp_path) == "3.11"
    pipfile.unlink()

    # Test setup.py (python_requires)
    setup_py = tmp_path / "setup.py"
    setup_py.write_text("setup(\n    python_requires='>=3.9',\n)\n", encoding="utf-8")
    assert detect_project_python_version(tmp_path) == "3.9"

    # Test setup.py (classifiers fallback picks highest/best version)
    setup_py.write_text("setup(\n    classifiers=[\n        'Programming Language :: Python :: 3.10',\n        'Programming Language :: Python :: 3.11',\n    ]\n)\n", encoding="utf-8")
    assert detect_project_python_version(tmp_path) == "3.11"
    setup_py.unlink()

    # Test local .venv precedence
    venv_dir = tmp_path / ".venv"
    venv_dir.mkdir()
    (venv_dir / "pyvenv.cfg").write_text("version = 3.12.3\n", encoding="utf-8")
    setup_py.write_text("setup(classifiers=['Programming Language :: Python :: 3.8'])\n", encoding="utf-8")
    assert detect_project_python_version(tmp_path) == "3.12"
    import shutil
    shutil.rmtree(venv_dir)
    setup_py.unlink()

    # Test setup.cfg
    setup_cfg = tmp_path / "setup.cfg"
    setup_cfg.write_text("[options]\npython_requires = >=3.11\n", encoding="utf-8")
    assert detect_project_python_version(tmp_path) == "3.11"
    setup_cfg.unlink()

    # Non-existent/empty
    assert detect_project_python_version(tmp_path) is None


def test_discover_python_environments(tmp_path):
    from pymolt.ingestion.detect import discover_python_environments
    venv_dir = tmp_path / ".venv"
    venv_dir.mkdir()
    (venv_dir / "pyvenv.cfg").write_text("version = 3.11.4\n", encoding="utf-8")
    envs = discover_python_environments(tmp_path)
    assert any(e.name.startswith(".venv") for e in envs)


def test_extract_declared_requirements(tmp_path):
    # Test requirements.txt
    req_txt = tmp_path / "requirements.txt"
    req_txt.write_text("Flask>=0.10\njsonschema>=3.0.1\n# comment\n", encoding="utf-8")
    reqs = extract_declared_requirements(req_txt)
    assert reqs["flask"] == "Flask>=0.10"
    assert reqs["jsonschema"] == "jsonschema>=3.0.1"

    # Test pyproject.toml
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text("[project]\ndependencies = [\n    'Flask>=0.10',\n    'jsonschema>=3.0.1'\n]\n", encoding="utf-8")
    reqs = extract_declared_requirements(pyproject)
    assert reqs["flask"] == "Flask>=0.10"
    assert reqs["jsonschema"] == "jsonschema>=3.0.1"

    # Test setup.py
    setup_py = tmp_path / "setup.py"
    setup_py.write_text("setup(\n    install_requires=[\n        'Flask>=0.10',\n        'jsonschema>=3.0.1',\n    ]\n)\n", encoding="utf-8")
    reqs = extract_declared_requirements(setup_py)
    assert reqs["flask"] == "Flask>=0.10"
    assert reqs["jsonschema"] == "jsonschema>=3.0.1"

    # Test setup.cfg
    setup_cfg = tmp_path / "setup.cfg"
    setup_cfg.write_text("[options]\ninstall_requires =\n    Flask>=0.10\n    jsonschema>=3.0.1\n", encoding="utf-8")
    reqs = extract_declared_requirements(setup_cfg)
    assert reqs["flask"] == "Flask>=0.10"
    assert reqs["jsonschema"] == "jsonschema>=3.0.1"
