"""Target-environment HINT emitter — pymolt does not build environments.

pymolt never provisions a venv, container, or Dockerfile: it only tells the engineer what to
build and how to point pymolt at it afterwards. ``build_target_hint`` is pure/read-only (it may
read the project's existing ``Dockerfile``, but never writes or runs anything) and returns a
:class:`TargetHint` — a derived Dockerfile suggestion (when one can be derived), the ``uv``
commands that would create an equivalent venv, and the ready-to-copy
``pymolt contract capture --when post-migration ...`` command to run once the engineer has
built the environment themselves.

``derive_target_dockerfile`` (and its ``_rewrite_from_line`` helper) is a pure string transform
(no filesystem, no subprocess) so it is unit-testable in isolation.
"""

from __future__ import annotations

import re
from pathlib import Path

from pydantic import BaseModel, Field

_HEADER_TEMPLATE = (
    "# Generated by pymolt env — derived from Dockerfile with Python -> {target}.\n"
    "# Review before use; the original Dockerfile is untouched.\n"
)

# Matches a `FROM <image>[:<tag>] [AS <stage>]` line and captures the pieces we
# might rewrite: the image name, the tag (version + optional -suffix), and any
# trailing "AS stage".
_FROM_RE = re.compile(
    r"^(?P<prefix>FROM\s+)(?P<image>[\w./-]+)(?P<tagsep>:(?P<tag>[\w.\-]+))?(?P<rest>.*)$"
)

# A python version embedded directly in the tag, e.g. "3.6", "3.6.1", "3.6-alpine".
_VERSION_IN_TAG_RE = re.compile(r"^(?P<version>\d+\.\d+(?:\.\d+)?)(?P<suffix>.*)$")

# `pythonX.Y`-style image/tag references (e.g. a base named "python3.6").
_PYTHON_DOTTED_RE = re.compile(r"python(?P<version>\d+\.\d+(?:\.\d+)?)")


def _rewrite_from_line(line: str, target_python: str) -> str:
    match = _FROM_RE.match(line)
    if not match:
        return line

    image = match.group("image")
    tag = match.group("tag")
    rest = match.group("rest") or ""

    if image.lower() == "python" or image.lower().endswith("/python"):
        if tag is None:
            return line
        ver_match = _VERSION_IN_TAG_RE.match(tag)
        if not ver_match:
            return line
        suffix = ver_match.group("suffix")
        new_tag = f"{target_python}{suffix}"
        return f"{match.group('prefix')}{image}:{new_tag}{rest}"

    # Non-`python` base image, but the tag itself embeds a python version
    # (e.g. `pythonX.Y`-style references) — swap just the version digits.
    if tag and _PYTHON_DOTTED_RE.search(tag):
        new_tag = _PYTHON_DOTTED_RE.sub(f"python{target_python}", tag)
        return f"{match.group('prefix')}{image}:{new_tag}{rest}"

    return line


# Word-boundary match on "requirements.txt" that does NOT also match
# "requirements-dev.txt" etc. (the boundary before "requirements" already excludes
# a preceding hyphen/word character; the boundary after ".txt" is the extension end).
_REQUIREMENTS_RE = re.compile(r"(?<![\w-])requirements\.txt\b")


def derive_target_dockerfile(
    dockerfile_text: str, target_python: str, manifest_name: str | None,
    dev_manifest_name: str | None = None,
) -> str:
    """Return a derived Dockerfile: python base images bumped to ``target_python``,
    with any ``requirements.txt`` reference swapped to ``manifest_name`` (when given).

    When ``dev_manifest_name`` is given, a ``COPY <dev_manifest_name> ./`` +
    ``RUN pip install -r <dev_manifest_name>`` pair is appended right after the main
    manifest's ``RUN pip install -r ...`` line, so the built image can also run the
    (post-migration) test suite. If no such anchor line exists, the dev-install
    lines are appended at the end of the Dockerfile instead.

    Pure function — no filesystem access — so it's directly unit-testable.
    """
    lines = dockerfile_text.splitlines(keepends=True)
    out_lines: list[str] = []
    dev_lines_inserted = False
    for line in lines:
        stripped = line.lstrip()
        if stripped.upper().startswith("FROM"):
            leading_ws = line[: len(line) - len(stripped)]
            trailing = ""
            body = stripped
            for nl in ("\r\n", "\n", "\r"):
                if body.endswith(nl):
                    trailing = nl
                    body = body[: -len(nl)]
                    break
            rewritten = _rewrite_from_line(body, target_python)
            out_lines.append(f"{leading_ws}{rewritten}{trailing}")
        else:
            out_lines.append(line)
            if (
                dev_manifest_name
                and not dev_lines_inserted
                and re.search(r"^\s*RUN\s+pip\s+install\s+-r\s", line, re.IGNORECASE)
            ):
                out_lines.append(f"COPY {dev_manifest_name} ./\n")
                out_lines.append(f"RUN pip install -r {dev_manifest_name}\n")
                dev_lines_inserted = True

    text = "".join(out_lines)
    if manifest_name:
        text = _REQUIREMENTS_RE.sub(manifest_name, text)

    if dev_manifest_name and not dev_lines_inserted:
        if not text.endswith("\n"):
            text += "\n"
        text += f"COPY {dev_manifest_name} ./\n"
        text += f"RUN pip install -r {dev_manifest_name}\n"

    header = _HEADER_TEMPLATE.format(target=target_python)
    return f"{header}{text}"


class TargetHint(BaseModel):
    """What the engineer should build to get a runnable target-Python environment, and how
    to point pymolt at it afterwards. A SUGGESTION only — pymolt never runs any of this."""

    target_python: str
    manifest: str | None = None
    suggested_dockerfile: str | None = None   # None if the project has no Dockerfile to derive from
    suggested_uv_commands: list[str] = Field(default_factory=list)
    capture_hint: str = ""
    notes: list[str] = Field(default_factory=list)


_SUGGESTED_VENV_DIR = ".venv-target"


def build_target_hint(
    project_dir: str | Path, target_python: str, manifest: str | None = None,
) -> TargetHint:
    """Build a :class:`TargetHint` for ``project_dir`` — pure/read-only: may read the
    project's ``Dockerfile`` if present, but never writes a file or runs a subprocess.

    ``manifest`` is the target manifest path (e.g. from ``assess``'s
    ``requirements-target.txt``); when omitted, the Dockerfile/uv suggestions still come
    back, just without an install step, and a note flags the gap.
    """
    project_path = Path(project_dir)
    notes: list[str] = []

    manifest_name = Path(manifest).name if manifest else None

    dockerfile_path = project_path / "Dockerfile"
    suggested_dockerfile: str | None = None
    if dockerfile_path.is_file():
        suggested_dockerfile = derive_target_dockerfile(
            dockerfile_path.read_text(encoding="utf-8"), target_python, manifest_name,
        )
    else:
        notes.append(
            f"No Dockerfile found at {dockerfile_path} — no derived Dockerfile suggested."
        )

    suggested_uv_commands = [f"uv venv {_SUGGESTED_VENV_DIR} --python {target_python}"]
    if manifest_name:
        suggested_uv_commands.append(
            f"uv pip install -r {manifest_name} --python {_SUGGESTED_VENV_DIR}/bin/python"
        )
    else:
        notes.append(
            "No manifest given — pass one (e.g. the requirements-target.txt from assess) "
            "to get an install command."
        )

    python_hint = f"{_SUGGESTED_VENV_DIR}/bin/python"
    capture_hint = (
        f"pymolt contract capture --when post-migration --mode tests -- "
        f"{python_hint} -m pytest tests/"
    )

    return TargetHint(
        target_python=target_python,
        manifest=manifest_name,
        suggested_dockerfile=suggested_dockerfile,
        suggested_uv_commands=suggested_uv_commands,
        capture_hint=capture_hint,
        notes=notes,
    )
