"""Files pymolt itself writes, and the one predicate that recognizes them.

Anything pymolt emits (the pinned target manifests) must never be re-detected
as an *input* by any phase — otherwise scan counts the tool's own output as a
project manifest and assess feeds its previous resolution back into the next
one. Both discovery and ingestion share this predicate so the rule cannot
drift between them.
"""

from __future__ import annotations

from pathlib import Path

GENERATED_NAMES = {"requirements-target.txt", "environment-target.yml"}
GENERATED_HEADER = "# generated by pymolt"


def is_pymolt_generated(item: Path) -> bool:
    """True for a file pymolt emitted (by canonical name, or its header line)."""
    if item.name.lower() in GENERATED_NAMES:
        return True
    try:
        with item.open("r", encoding="utf-8", errors="ignore") as fh:
            first_line = fh.readline()
    except OSError:
        return False
    return first_line.strip().lower().startswith(GENERATED_HEADER)
