from pymolt.setup.target_hint import build_target_hint, derive_target_dockerfile


def test_derive_target_dockerfile_multi_stage():
    text = (
        "FROM python:3.6-alpine AS build\n"
        "COPY requirements.txt .\n"
        "RUN pip install -r requirements.txt\n"
        "\n"
        "FROM python:3.6.1\n"
        "COPY --from=build /app /app\n"
        "RUN pip install -r requirements-dev.txt\n"
        "\n"
        "FROM node:20\n"
    )

    out = derive_target_dockerfile(text, "3.13", "requirements-target.txt")

    assert "FROM python:3.13-alpine AS build" in out
    assert "FROM python:3.13\n" in out
    assert "FROM node:20" in out
    assert "COPY requirements-target.txt ." in out
    assert "RUN pip install -r requirements-target.txt" in out
    # requirements-dev.txt must be left untouched (not matched by the word-boundary swap).
    assert "RUN pip install -r requirements-dev.txt" in out
    assert "requirements-target-dev.txt" not in out
    assert out.startswith(
        "# Generated by pymolt env — derived from Dockerfile with Python -> 3.13.\n"
        "# Review before use; the original Dockerfile is untouched.\n"
    )


def test_derive_target_dockerfile_with_dev_manifest():
    text = (
        "FROM python:3.6-alpine\n"
        "COPY requirements.txt .\n"
        "RUN pip install -r requirements.txt\n"
    )

    out = derive_target_dockerfile(
        text, "3.13", "requirements-target.txt", "requirements-dev.txt",
    )

    assert "COPY requirements-dev.txt ./" in out
    assert "RUN pip install -r requirements-dev.txt" in out
    # dev install lines should come after the main manifest install line.
    main_idx = out.index("RUN pip install -r requirements-target.txt")
    dev_copy_idx = out.index("COPY requirements-dev.txt ./")
    dev_run_idx = out.index("RUN pip install -r requirements-dev.txt")
    assert main_idx < dev_copy_idx < dev_run_idx


def test_build_target_hint_writes_and_runs_nothing(tmp_path):
    (tmp_path / "Dockerfile").write_text("FROM python:3.6\n", encoding="utf-8")
    before = sorted(tmp_path.iterdir())

    hint = build_target_hint(tmp_path, "3.13", manifest="requirements-target.txt")

    assert sorted(tmp_path.iterdir()) == before  # nothing written
    assert hint.target_python == "3.13"
    assert hint.manifest == "requirements-target.txt"
    assert hint.suggested_dockerfile is not None
    assert "FROM python:3.13" in hint.suggested_dockerfile
    assert any("uv venv" in cmd for cmd in hint.suggested_uv_commands)
    assert any("requirements-target.txt" in cmd for cmd in hint.suggested_uv_commands)
    assert "pymolt contract capture --when post-migration" in hint.capture_hint


def test_build_target_hint_no_dockerfile_notes_the_gap(tmp_path):
    hint = build_target_hint(tmp_path, "3.13")

    assert hint.suggested_dockerfile is None
    assert any("No Dockerfile" in n for n in hint.notes)
    assert any("No manifest" in n for n in hint.notes)
